# -*- org-confirm-babel-evaluate: nil; org-src-preserve-indentation: t -*-
#+title: Advent of Code in K
#+date: 2026-09-12
#+tags: array-lang, k
#+options: toc:nil

Let's do some k.

#+HTML: <!--more-->

They say the best way to learn a language is to write "useful" programs in it. Screw that, I say, let's do some fun puzzles instead!
I hope[fn:1] this will not be another [[https://tony-zorman.com/posts/aoc-in-bqn.html][20'000 word post]], but you never know.
Seriously, though, I will try to be a bit more terse—get it?—than in previous posts, if only to save my sanity.

* Introduction
** Setup

I'll just quote the BQN post here, as this part is sort of the same:

#+begin_quote
Advent of Code is a yearly puzzle-coding-challenge-thing, in which one has to solve two riddles every day from the 1st until the 25th of December, with the second part of each puzzle being unknown until one solves the first one. I’ve found it to be a great way to learn the basics of a language—how it “feels”.

The puzzles are accompanied by an endearing—and at times pretty funny—story. I will, however, leave out most of it for this post, as I feel like it would distract too much from the point I’m trying to make.
#+end_quote

** Disclaimer

I don't actually know this language. Much like the BQN post, this post
is mostly aimed at myself—writing things down is a great way to learn
them, it turns out. As a result, expect many little inaccuracies and
probably also some more major oopsies.[fn:2] If you actually want a good
introduction to the language, I recommend [[https://razetime.github.io/ngn-k-tutorial/][razetime's tutorial]] and the
[[https://github.com/kparc/kcc][kparc crash course]].

** Conventions
:PROPERTIES:
:ID:       ce2d4f45-33e0-458a-a36f-4be6c7a4e66c
:END:

This article is written in a literate style; see [[/posts/interactive.html][this post]] for more information.
Right now, this just means that whenever you see a code block defining a variable or function

#+BEGIN_SRC k
aliteralone:1; Add:+;
two:((1 1); (2 3))
#+END_SRC

#+RESULTS:

then expect it to carry over to the next code block. Additionally, most
examples will be presented in a REPL-esque fashion; input is indented by
a space, and output is flush to the left. Line comments start with ~ /~.[fn:3]

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
Add[aliteralone;aliteralone] / M-Expressions can be used for function application
#+END_SRC

#+RESULTS:
#+begin_SRC k
 Add[aliteralone;aliteralone] / M-Expressions can be used for function application
2
#+end_SRC

Think of each day as introducing its own namespace, though; things would
get out of hand fast otherwise, considering the tersity of most names!

Additionally, for better search (~Full solution:~), I will include the
full solution at the end of each day.

* A crash course on syntax

Here is an entirely too short crash course on the syntax of k. If you've
read the [[https://tony-zorman.com/posts/aoc-in-bqn.html#a-crash-course-on-syntax][BQN version]] of this, a lot of it will feel familiar, although
sometimes in an uncanny valley type of way.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
1+4+6 / 1+(4+6)
2*4+6 / 2*(4+6)
#+END_SRC

#+RESULTS:
#+begin_SRC k
 1+4+6 / 1+(4+6)
11
 2*4+6 / 2*(4+6)
20
#+end_SRC

As with most (all?) array languages, builtin functions—​/verbs/, in k
parlance—have the same precedence, and expressions are evaluated
strictly right to left.

Assignment uses ~:~​—one of its many, many uses—and multiple expressions
on one line are separated by ~;~:[fn:4]

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:a:2*4+6 / Another use for : is "right"
b:1+1    / By default, you won't see the result of an assignment
a
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :a:2*4+6 / Another use for : is "right"
20
 b:1+1    / By default, you won't see the result of an assignment

 a
20
#+end_SRC

*** Lists and atoms
:PROPERTIES:
:ID:       a30bdeea-815c-46e6-9f15-a3f5c95f22ca
:END:

The fundamental data structure in k is the list. Some homogeneous lists
(e.g., numbers or symbols) can be created just by juxtaposition; general
lists use parentheses and semicolons. Strings are lists of characters.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
1 2 3
(1;2;3)
("hi";42;1 2 3)
"a" "b" / Error!
("a";"b")
`a`b    / This is ok
#+END_SRC

#+RESULTS:
#+begin_SRC k
 1 2 3
1 2 3
 (1;2;3)
1 2 3
 ("hi";42;1 2 3)
("hi"
 42
 1 2 3)
 "a" "b" / Error!
'type
 "a" "b" / Error!
     ^
 ("a";"b")
"ab"
 `a`b    / This is ok
(`"a"
 `"b")
#+end_SRC

A symbol in K starts with a backquote, followed by some string of ASCII
characters. You can think of ~`a~ as an analogue of ~'a~ in a Lisp. In
general, K seems to be inspired quite a bit by that family of
languages, as we'll see when we get to functions and indexing.

Unlike many other array languages, k does not have "proper"
multidimensional arrays; instead, they're represented by nested lists.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
3 3#!9 / ! is iota and # is reshape
#+END_SRC

#+RESULTS:
#+begin_SRC k
 3 3#!9 / ! is iota and # is reshape
(0 1 2
 3 4 5
 6 7 8)
#+end_SRC

This also means that these "arrays" can be ragged without any troubles.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
(0 1;2 3 4;5)
#+END_SRC

#+RESULTS:
#+begin_SRC k
 (0 1;2 3 4;5)
(0 1
 2 3 4
 5)
#+end_SRC

Indenting things by one additional space in the REPL turns off the kind
of pretty-printing,[fn:5] though you can often also just /enclose/ (~,~)
the result.

#+begin_SRC k :results repl :exports results :wrap SRC k
,3 3#!9
#+end_SRC

#+RESULTS:
#+begin_SRC k
 ,3 3#!9
,(0 1 2;3 4 5;6 7 8)
#+end_SRC

*** Nouns, verbs, and adverbs

Roughly, instead of variables, operators, and higher-order functions, K
instead talks about /nouns/, /verbs/, and /adverbs/.

Nouns are.

-----

Verbs act on nouns. More specifically, they're builtin functions, and
more or less equivalent to what an operator would be in other
languages—that is, they are (or, rather, can be) written using infix
notation, and take one (to the right) or two (to the left and right)
arguments. For example, the symbol ~%~ is a square root function when
supplied with one argument, and floating point division in the two
argument case:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
%8     / Square root of 8
%4 6   / Square root of 4 and of 6
1%2    / ½
#+END_SRC

#+RESULTS:
#+begin_SRC k
 %8     / Square root of 8
2.8284271247461903
 %4 6   / Square root of 4 and of 6
2.0 2.449489742783178
 1%2    / ½
0.5
#+end_SRC

The fact that ~%~ transparently works on an array is called /scalar
pervasion/, and is one of the backbones of a lot of array languages.[fn:12]

Instead of these verbs having a "unary" and "binary" case, we instead
say they are /monadic/ or /dyadic/. Greek is better than Latin, or something.
In K, this is actually a little bit more complicated, as the mere
presence of one or two arguments is not enough to disambiguate a
function: you also need to know about the types of the arguments. More
on that later.

-----

Adverbs modify verbs; you can think of them as special notation for
higher-order functions, from a time when perhaps this wasn't a thing
people thought about much.

For example, /each/, ~f'~​, maps ~f~ over ~x~; this might be written ~map f x~ in
Haskell, or ~x.map(f)~ in Rust.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
{x+1}'1 2 3 4 / We'll talk about user-defined functions soon
#+END_SRC

#+RESULTS:
#+begin_SRC k
 {x+1}'1 2 3 4 / We'll talk about user-defined functions soon
2 3 4 5
#+end_SRC

Two of the most useful adverbs are /fold/ (~F/~) and /scan/ (~F\~), both
of which are the left variants of these respective operations.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
+/!9      / Sum up all numbers from 0 to 8
-/!4      / Left fold: ((0-1)-2)-3
{y-x}/|!4 / Emulating a right fold using reverse |x
+\!9      / Scan shows intermediate results
#+END_SRC

#+RESULTS:
#+begin_SRC k
 +/!9      / Sum up all numbers from 0 to 8
36
 -/!4      / Left fold: ((0-1)-2)-3
-6
 {y-x}/|!4 / Emulating a right fold using reverse |x
-2
 +\!9      / Scan shows intermediate results
0 1 3 6 10 15 21 28 36
#+end_SRC

-----

There are no precedence rules for verbs in K, but adverbs still bind
tighter than verbs, since they need one of the latter to be correctly
specified. That is, something like ~,//~ is grouped like ~(,/)/~.

*** Lambdas

You've already seen some user-defined functions, like ~{x+1}~ or ~{y-x}~
above: they're written with curly braces, and each function can have up
to three implicit arguments that you can use: ~x~, ~y~, and ~z~. These
are very much like ~α~ and ~ω~ in APL, or ~𝕨~ and ~𝕩~ in BQN.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
{x+1} 5
{x+y}[3;4]
dbl:{x+x}; dbl 5
#+END_SRC

#+RESULTS:
#+begin_SRC k
 {x+1} 5
6
 {x+y}[3;4]
7
 dbl:{x+x}; dbl 5
10
#+end_SRC

User-defined functions are automatically nouns instead of verbs, so
they're treated like variables, instead of the builtin functions.[fn:6]
This has a few implications: first, they can't be used infix, and one
instead has to resort to one of the many types of function application
syntaxes, some of which we've already seen above (and one of which is
M-Expression syntax!)

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
Add:{x+y}
Add[2;3]  / M-Expression
Add[2]    / Functions are automatically curried!
Add[2][3]
Add[2] 3  / Juxtaposition also works
Add[2]@3  / Another verb for application
Add.(2;3) / TODO
#+END_SRC

#+RESULTS:
#+begin_SRC k
 Add:{x+y}

 Add[2;3]  / M-Expression
5
 Add[2]    / Functions are automatically curried!
{x+y}[2;]
 Add[2][3]
5
 Add[2] 3  / Juxtaposition also works
5
 Add[2]@3  / Another verb for application
5
 Add.(2;3) / TODO
5
#+end_SRC

Some of these are necessary in one situation or another. For example,
monadic ~%~ gives the square root of a number, so ~Add[2] %5~ should
yield \(2 + \sqrt{5}\), but instead yields a syntax error. The ~Add[2]~,
being a noun, is treated as another argument to ~%~ and it tries to do
its dyadic overload, /divide/. To fix this one has to use ~@~.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
Add[2] %5 /error
Add[2]@%5 /ok
#+END_SRC

#+RESULTS:
#+begin_SRC k
 Add[2] %5 /error
'type
 Add[2] %5 /error
        ^
 Add[2]@%5 /ok
4.23606797749979
#+end_SRC

-----

Indexing into an array uses the same syntax as function application:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:a:3 3#!9
a[0;1]  / Single element
a[2]    / Row
a[0][1] / Single element
a[0] 1  / Juxtaposition also works
a[0]@1  / Another verb for application
a.(0;1) / TODO
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :a:3 3#!9
(0 1 2
 3 4 5
 6 7 8)
 a[0;1]  / Single element
1
 a[2]    / Row
6 7 8
 a[0][1] / Single element
1
 a[0] 1  / Juxtaposition also works
1
 a[0]@1  / Another verb for application
1
 a.(0;1) / TODO
1
#+end_SRC

There's again some different behaviour when it comes to ~@~ and ~.~:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:a:3 3#!9
a@0 1    / First and second row
a.0 1    / Element at index 0 1
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :a:3 3#!9
(0 1 2
 3 4 5
 6 7 8)
 a@0 1    / First and second row
(0 1 2
 3 4 5)
 a.0 1    / Element at index 0 1
1
#+end_SRC

*** Type-based overloading

Verbs in K are overloaded quite a bit; for example, ~!~ has as many as
seven (7) meanings, depending on the types of its parameters:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
!10       /   !i is enum
!1 2 3    /   !I is odometer
`a`b!1 2  /  x!y is dict
!`a`b!1 2 /   !d is keys
3!10 12   /  i!I is mod
-3!10 12  / -i!I is div (really!)
/ … and so on
#+END_SRC

#+RESULTS:
#+begin_SRC k
 !10       /   !i is enum
0 1 2 3 4 5 6 7 8 9
 !1 2 3    /   !I is odometer
(0 0 0 0 0 0
 0 0 0 1 1 1
 0 1 2 0 1 2)
 `a`b!1 2  /  x!y is dict
!/+((`"a";1)
    (`"b";2))
 !`a`b!1 2 /   !d is keys
(`"a"
 `"b")
 3!10 12   /  i!I is mod
1 0
 -3!10 12  / -i!I is div (really!)
3 4
 / … and so on
#+end_SRC

Needless to say, this turns reading K into quite an adventure. To make
this slightly easier, I'll do what the REPL does, and indicate the types
by a single letter; instead of "dyadic ~!~", I'll talk about ~i!I~
instead. Here's the relevant table:

#+BEGIN_SRC
notation: [c]har [i]nt [n]umber(int|float|char) [s]ymbol [a]tom [d]ict
          [f]unc(monad) [F]unc(dyad) [xyz]any
#+END_SRC

Upper case letters indicate a list of the respective type. These are
(almost) the same letters that K gives you when you ask it the type of
things with ~@x~:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
@1
@1 2 3
@`a!1  / We'll talk about dicts at some point, I promise
@"a"   / A single characters in ""s is automatically a char
@"abc"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 @1
`i
 @1 2 3
`I
 @`a!1  / We'll talk about dicts at some point, I promise
`m
 @"a"   / A single characters in ""s is automatically a char
`c
 @"abc"
`C
#+end_SRC


* Days 1–5
** [[https://github.com/slotThe/advent/blob/master/aoc2020/k-solutions/day01.k][Day 1]]

We're going on vacation! However, of course we'll first have to do some
work, in order to earn the exotic local currency used on the island we'd
like to travel to.

Today, the elves want us to help them with their expense records; for
part one, we have to find the two entries in the input that sum up to
2020 and multiply them together. The file is just a big list of
integers, separated by newlines; one of the many uses of the colon in K
is for reading a file line by line with ~0:~.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
10# 0:"./aoc/2020/day01.txt"  / take (i#y) the first 10 lines, for display reasons
`I$ 0:"./aoc/2020/day01.txt"  / s$y is cast, and `I means a list of integers
i:`I$0:"./aoc/2020/day01.txt" / call this list i
#i                            / #x is length
#+END_SRC

#+RESULTS:
#+begin_SRC k
 10# 0:"./aoc/2020/day01.txt"  / take (i#y) the first 10 lines, for display reasons
("1895"
 "1732"
 "1660"
 "1658"
 "1878"
 "367"
 "2010"
 "1989"
 "431"
 "1946")
 `I$ 0:"./aoc/2020/day01.txt"  / s$y is cast, and `I means a list of integers
1895 1732 1660 1658 1878 367 2010 1989 431 1946 1614 2003 945 1856 1934 1937 1781 1947 1991 1917 1604 1707 1966 1959 1182 1828 1880 1908 1942 1687 1611 1922 1913 1803 1976 1718 1885 1971 2000 1912 1981 1776 1901 1941 1935 1977 1907 189..
 i:`I$0:"./aoc/2020/day01.txt" / call this list i

 #i                            / #x is length
200
#+end_SRC

The file is only 200 entries long, so we don't have to do anything fancy
here, and a simple outer product should be enough: compare each number
with all other numbers, and if the sum is 2020 we're good. K has /each
left/ (~x F\: y~) and /each right/ (~x F/: y~) for purposes like this.
For example, the latter would apply ~F~ to ~a~ and ~y~, for all elements
~a~ of ~x~.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:x:!4       / !i is iota/range
:y:!5
x +\: y     / (0 + y; 1 + y; and so on)
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :x:!4       / !i is iota/range
0 1 2 3
 :y:!5
0 1 2 3 4
 x +\: y     / (0 + y; 1 + y; and so on)
(0 1 2 3 4
 1 2 3 4 5
 2 3 4 5 6
 3 4 5 6 7)
#+end_SRC

So, the strategy is: form an outer product of ~i~ with itself under
addition, compare each entry with 2020, get a mask of all hits, get the
first hit, use these values to index into ~i~, and multiply the numbers
together. Getting the indices of hits can be done with /where/ (~&I~);
everything else just uses operations we've seen already, stuck together
in new and creative ways.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
&1 0 1 0 1 0              / Only give me the indices that are 1
& 2020= i+\:i             / indices of hits
{i@x}'& 2020= i+\:i       / indexed back into i
**/{i@x}' & 2020= i+\:i   / and multiplied (and the first of those)
#+end_SRC

#+RESULTS:
#+begin_SRC k
 &1 0 1 0 1 0              / Only give me the indices that are 1
0 2 4
 & 2020= i+\:i             / indices of hits
(110 174
 174 110)
 {i@x}'& 2020= i+\:i       / indexed back into i
(1191 829
 829 1191)
 ,**/{i@x}' & 2020= i+\:i   / and multiplied (and the first of those)
987339
#+end_SRC

-----

For part two, we instead need to find the three numbers that sum up
to 2020. As we are still only considering a list of length 200, this
doesn't need any new algorithmic insight; we can just repeat what we've
already done, using an iterative /each left/.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
**/{i@x}' & 2020= i+\:i+\:i
#+END_SRC

#+RESULTS:
#+begin_SRC k
 ,**/{i@x}' & 2020= i+\:i+\:i
259521570
#+end_SRC

We could have also written this without the curly braces:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
**/(i@)' & 2020= i+\:i+\:i
#+END_SRC

#+RESULTS:
#+begin_SRC k
 ,**/(i@)' & 2020= i+\:i+\:i
259521570
#+end_SRC

This showcases an important feature of K, which I'll make use of quite a
bit going forward: trains!

#+HTML: <details><summary>Trains in K</summary>

A train consists of a sequence of functions and arguments (verbs and
nouns), that is however being terminated by a verb. Normally, this would
not have any actual meaning as an expression, as it's not given an
argument (noun) to act upon. However, interpreting this as a kind of
function composition, we can use this to glue together verbs into
something bigger, without naming arguments at all. This is usually
called /tacit programming/.[fn:7]

For example, ~A:{x+y}~ could just be written as ~A:+~. Since verbs in K
have both a monadic and a dyadic meaning, the way in which one uses them
in trains must be unambiguous. For that, yet another overload of the
colon is used—a verb followed by a colon indicates that it's monadic, so
while ~A:+~ signifies that the ~A~ function adds two arrays, ~T:+:~
instead defines a function ~T~ for transposition.

Here's a slightly more complicated example: given two \(n \times n\)-matrices \(A = (a_{ij})\) and \(B = (b_{ij})\), their product at the index \((i,j)\) is defined by
\[
    (A B)_{ij} = \sum_{k=1}^{n} a_{ik}b_{kj}.
\]

Let's write a K function to compute the matrix multiplication of two square matrices.[fn:8]

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
Mn:{+/'x*\:y}   / Matrix multiplication, "normal"
Mt:+/'*\:       / Matrix multiplication, tacit
:A:3 3#!9
:B:3 3#5+!9
Mn[A;B]
Mn[A;B]~Mt[A;B] / Dyadic ~ is "matches?"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 Mn:{+/'x*\:y}   / Matrix multiplication, "normal"

 Mt:+/'*\:       / Matrix multiplication, tacit

 :A:3 3#!9
(0 1 2
 3 4 5
 6 7 8)
 :B:3 3#5+!9
(5 6 7
 8 9 10
 11 12 13)
 Mn[A;B]
(30 33 36
 102 114 126
 174 195 216)
 Mn[A;B]~Mt[A;B] / Dyadic ~ is "matches?"
1
#+end_SRC

Why would anyone ever program like this? Well, besides the fact that
it's fun, it's just another case of really internalising the "names
don't matter" mantra. Since the implementation ~+/'*\:~ has exactly as
many characters as the name ~matmul~, perhaps there is something to that
line of thinking.

#+HTML: </details>
-----

Full solution:

#+BEGIN_SRC k
i:`I$0:"./aoc/2020/day01.txt"
987339   = **/(i@)'&2020=i+\:i
259521570= **/(i@)'&2020=i+\:i+\:i
#+END_SRC

#+RESULTS:

** [[https://github.com/slotThe/advent/blob/master/aoc2020/k-solutions/day02.k][Day 2]]

Today we have to help a shopkeeper fix the computer system of the
Toboggan Rental Shop at the airport. Of course, to ensure the safety of
the system, all passwords must follow a strict policy. Part 1 asks us
how many valid passwords there are in the bunch.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
0:"./aoc/2020/day02.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 0:"./aoc/2020/day02.txt"
1
#+end_SRC

Each line indicates the lowest and highest number of times the given
letter may occur in the password; so ~3-4 j: tjjj~ would say that ~j~
must occur three, and may at most occur four, times in the string
~tjjj~. Let's do some parsing first.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:test: *" "\' 0:"./aoc/2020/day02.txt" / C\ is split
{(.'"-"\x 0;*-1_x 1;x 2)} test
:(f;c;s): + {(`I$"-"\x 0;*-1_x 1;x 2)}' " "\' 0:"./aoc/2020/day02.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :test: *" "\' 0:"./aoc/2020/day02.txt" / C\ is split
("3-4"
 "j:"
 "tjjj")
 {(.'"-"\x 0;*-1_x 1;x 2)} test
(3 4
 "j"
 "tjjj")
 :(f;c;s): + {(`I$"-"\x 0;*-1_x 1;x 2)}' " "\' 0:"./aoc/2020/day02.txt"
((3 4;7 10;7 13;4 13;3 11;5 6;7 10;1 10;5 6;12 13;1 4;10 14;1 3;3 4;15 16;3 4;10 12;10 11;4 11;2 4;3 8;5 9;9 16;4 5;2 11;4 7;2 4;8 9;2 9;3 4;16 18;2 12;8 9;1 3;2 10;8 11;3 14;2 3;1 6;1 10;2 11;10 15;6 7;17 18;7 8;3 4;3 10;7 16;2 4;1 3;..
 "jhjlndzwwmbknwqwrvlprgnvrqsmxdqsqdhlwmbcgtsjmmhxbjmpdlfsscncblhdxxfbjstpjblgftpwgxddxptwnvvdbgxrzxdgpfrwkgxzgnkmwqrbdmqnlmbwlzhbqgdhhxnzfpgvrgxhsrmlfdbknstkxddtsdnspshzjqwqksgqgnknjnffghbxcrgfjdbsdxtmlhdjqbjtzxbwwskfznpbkxkkpbbggsmbl..
 ("tjjj";"nhhhhhgghphhh";"tpscbbstbdjsjbtcpj";"ckllmqzlvcsxpplqg";"nnrhnnnnnnnwsdnnnm";"ddddddb";"szfwzrbzzz";"wwwwwcwwwrpnwzwxww";"cgwppfwlwrwtnw";"bmmthmmhmmmbmmmmm";"gbbj";"kkkkkkkkkfkkkzk";"nndn";"wwpf";"qqqqqqqqqqqqrqqqq";"wwcg";..)
#+end_SRC

After splitting each line on spaces, we apply the function ~{(`I$"-"\x
0;-1_x 1;x 2)}~ to each element: it splits the first element, which
looks like ~15-34~, on the dash, and then again /casts/ the resulting
list of strings into a list of integers. For the second entry, ~j:~, we
/drop/ the last element by giving ~i_X~ a negative value as a left
argument.

At the very end, we /transpose/ the input, so that instead of a list of
three-element lists, we get three lists of the individual things to
consider: ~[f]requency~, ~[c]har~, and ~[s]tring~. This kind of
transposition is often used in array languages, as now one can really
make use of primitives working on arrays.

Checking whether a password is valid involves checking whether all
occurrences of a given char in the associated string lies in the
frequency interval. Comparing a char with its string is easy:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5# c=s   / All comparisons at once
+/' c=s  / Number of occurrences
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5# c=s   / All comparisons at once
(0 1 1 1
 0 1 1 1 1 1 0 0 1 0 1 1 1
 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1
 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0
 1 1 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0)
 +/' c=s  / Number of occurrences
3 9 3 4 12 6 5 12 5 12 2 13 3 2 16 2 13 5 2 5 5 14 16 2 2 2 12 8 14 4 16 14 4 9 15 3 17 1 10 5 8 2 7 14 4 3 3 3 3 4 6 14 10 2 10 11 13 3 8 5 4 9 5 10 6 10 11 5 2 11 1 14 3 7 3 6 9 4 5 6 11 12 1 5 8 8 2 19 4 2 11 5 5 0 3 10 14 2 10 1 8 ..
#+end_SRC

All that's left is to check the interval condition. Now, I have to say,
this brings us to a bit of an annoying corner of K, at least in my
opinion: the lack of proper ~<=~ and ~>=~ operators. They just don't
exist, so we'll have to do some logical transformations.[fn:10] Notice, for
example, that
\[
  x \in [a,b] \iff a \le x \land x \le b \iff x<a \oplus x<b+1
\]
Yes, this is a horribly roundabout way of expressing that particular
fact, but it can at least be implemented in K straightforwardly:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5# (0 1+)'f                / Turn b into b+1
5# (+/'c=s)<(0 1+)'f       / Comparison
5# 1=+/' (+/'c=s)<(0 1+)'f / XOR test
+/ 1=+/' (+/'c=s)<(0 1+)'f / Answer for part one
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5# (0 1+)'f                / Turn b into b+1
(3 5
 7 11
 7 14
 4 14
 3 12)
 5# (+/'c=s)<(0 1+)'f       / Comparison
(0 1
 0 1
 1 1
 0 1
 0 0)
 5# 1=+/' (+/'c=s)<(0 1+)'f / XOR test
1 1 0 1 0
 +/ 1=+/' (+/'c=s)<(0 1+)'f / Answer for part one
483
#+end_SRC

-----

The shopkeeper helpfully informs us that we've actually followed the
wrong policy! Instead of the scheme so far, the numbers in ~f~ indicate
but two 1-indexed positions in the string, and exactly one of those
positions must contain the given character. Not so bad, we just have to
slightly adjust the function for part 1.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5# f-1           / 0-indexed
5# s@'f-1        / Getting the letters
5# 1=+/'c=s@'f-1 / Exactly one
+/ 1=+/'c=s@'f-1 / Answer for part two
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5# f-1           / 0-indexed
(2 3
 6 9
 6 12
 3 12
 2 10)
 5# s@'f-1        / Getting the letters
("jj"
 "gp"
 "sj"
 "lp"
 "rn")
 5# 1=+/'c=s@'f-1 / Exactly one
0 0 1 1 1
 +/ 1=+/'c=s@'f-1 / Answer for part two
482
#+end_SRC

-----

Full solution:

#+BEGIN_SRC k
(f;c;s): + {(`I$"-"\x 0;*-1_x 1;x 2)}' " "\' 0:"./aoc/2020/day02.txt" /freq, char, string
483= +/1=+/'(+/'c=s)<(0 1+)'f /x ∈ [a,b] ⇔ x≤b∧x≥a ⇔ x<a ⊕ x<b+1
482= +/1=+/'c=s@'f-1
#+END_SRC

#+RESULTS:

** [[https://github.com/slotThe/advent/blob/master/aoc2020/k-solutions/day03.k][Day 3]]

Today, we'll have to safely manoeuvre a toboggan through a forest. As an
input, we get a map of the area, with the trees denoted by hashes:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
0:"./aoc/2020/day03.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 0:"./aoc/2020/day03.txt"
("...#...#..#....#..#...#..##..#."
 ".#..#.....#.#............###..."
 ".#...###....#.............##..#"
 "...##...##....#.....##..#.##..."
 ".....###.#.###..##.#.##.......#"
 "#...##.....#..........#..#.#.#."
 "......##.......##..#....#.#...."
 "....#.###.##..#.#..##.##....#.#"
 ".......#.......###.#.#.##.....#"
 ".........#.#....#..........#.#."
 ".#...##.....##.........#..#...."
 ".##....#.#.#...##......#......."
 "##.#.#..#....#....#....#...#.#."
 "##....#.#..##......#....##...#."
 "....#..#..##..#.###.......#.#.."
 ".....##....###...........#.#.##"
 "#.....##.........#....##......#"
 "........###.#..#....#....#....."
 "...#.......#.##..#.###......#.."
 "...............#..#....#.##...."
 "..#..###..#.#..#.........##..#."
 ..)
#+end_SRC

We're also helpfully informed that the pattern loops when going to the right, but not when going down.

We start at the upper left corner, and always move three squares to the
right and one square down. Our task for part 1 is to find out how many
trees we would hit this way.

For this, we can use another overload for ~/~ and ~\~: ~i f/~ is /n-do/
and ~i f\~ is /n-dos/. The former is perhaps easier to explain: it's
just a for-loop, in which you don't have access to the loop variable.
For example, ~5 (1+)/ 3~ is equivalent to

#+BEGIN_SRC
s = 3;
for _ in [0…5]: # inclusive!
  s += 1;
s                # 8
#+END_SRC

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5 (1+)/ 3
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5 (1+)/ 3
8
#+end_SRC

Some lisps call this ~dotimes~. The ~\~-variant just keeps track of all
intermediate results.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5 (1+)\ 3
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5 (1+)\ 3
3 4 5 6 7 8
#+end_SRC

We can use this /n-dos/ to generate all positions: since we're going
down one square in each step, just add ~1 3~ to the initial position of
~0 0~ that many times, wrapping around horizontally if necessary.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5# i:"#"=0:"./aoc/2020/day03.txt"     / #=1
r:#i; c:#*i                           / Rows and columns
,(r-1){(0;c)!'1 3+x}\(0;0)            / Indices of points
+/ (i.)' (r-1)((0;c)!'1 3+)\(0;0)     / Part one
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5# i:"#"=0:"./aoc/2020/day03.txt"     / #=1
(0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0
 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0
 0 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0
 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 1)
 r:#i; c:#*i                           / Rows and columns

 ,(r-1){(0;c)!'1 3+x}\(0;0)            / Indices of points
,(0 0;1 3;2 6;3 9;4 12;5 15;6 18;7 21;8 24;9 27;10 30;11 2;12 5;13 8;14 11;15 14;16 17;17 20;18 23;19 26;20 29;21 1;22 4;23 7;24 10;25 13;26 16;27 19;28 22;29 25;30 28;31 0;32 3;33 6;34 9;35 12;36 15;37 18;38 21;39 24;40 27;41 30;42 2;..
 +/ (i.)' (r-1)((0;c)!'1 3+)\(0;0)     / Part one
187
#+end_SRC

Two interesting things about this: first, we have to use /apply/ of the
form ~x.y~ instead of ~x@y~, because we don't want two rows at different
locations, but a single element.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
i@0 2    / first and third row
i.0 2    / element at index 0 2
#+END_SRC

#+RESULTS:
#+begin_SRC k
 i@0 2    / first and third row
(0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0
 0 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1)
 i.0 2    / element at index 0 2
0
#+end_SRC

Second, while ~i!I~ is /mod/, we actually have an array on the left,
which turns this into /dict/ instead! To do what we want, we have to
apply mod component-wise with /each/. Actually, maybe three interesting
things: K is one of the few languages where ~0!x~ actually returns ~x~
itself! This is more consistent, mathematically, but a lot of languages
forego that for, I suppose, ease of implementation.

-----

Part two gives us some additional slopes to consider:

#+begin_quote
- Right 1, down 1.
- Right 3, down 1. (This is the slope you already checked.)
- Right 5, down 1.
- Right 7, down 1.
- Right 1, down 2.
#+end_quote

Let's start by turning that part of our part one solution into a function.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
whee:{+/ (i.)' ((-*x)!r-1)((0;c)!'x+)\(0;0)} / x is a slope of the form (down;right)
*/whee' (1 1; 1 3; 1 5; 1 7; 2 1)            / Part two
#+END_SRC

#+RESULTS:
#+begin_SRC k
 whee:{+/ (i.)' ((-*x)!r-1)((0;c)!'x+)\(0;0)} / x is a slope of the form (down;right)

 ,*/whee' (1 1; 1 3; 1 5; 1 7; 2 1)            / Part two
4723283400
#+end_SRC

This uses a very non-obvious overload of ~!~: ~(-i)!I~ is not modding
with a negative number, but actually integer division of (all of) ~I~ by
~i~! No, I don't know why.

-----

Full solution:

#+BEGIN_SRC k
i:"#"=0:"./aoc/2020/day03.txt"; r:#i; c:#*i
whee:{+/(i.)'((-*x)!r-1)((0;c)!'x+)\(0;0)} / x is a slope of the form (down;right)
187       = one:whee 1 3
4723283400= one**/whee'(1 1;1 5;1 7;2 1)
#+END_SRC

#+RESULTS:

** [[https://github.com/slotThe/advent/blob/master/aoc2020/k-solutions/day04.k][Day 4]]

Today we are standing in an airport queue, and are tasked to manipulate
the passport validity check. Each passport is expected to have the
following fields:

- ~byr~ (Birth Year)
- ~iyr~ (Issue Year)
- ~eyr~ (Expiration Year)
- ~hgt~ (Height)
- ~hcl~ (Hair Color)
- ~ecl~ (Eye Color)
- ~pid~ (Passport ID)
- ~cid~ (Country ID)

Only passports that either have all of the fields, or are just missing
the ~cid~ field should be allowed. Parsing is always /so much fun/ in
array languages, so let's get on with it.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
,0:"./aoc/2020/day04.txt" / easier to see
1:"./aoc/2020/day04.txt"  / easier to work with
#+END_SRC

#+RESULTS:
#+begin_SRC k
 ,0:"./aoc/2020/day04.txt" / easier to see
1
 1:"./aoc/2020/day04.txt"  / easier to work with
,("hgt:176cm";"iyr:2013";"hcl:#fffffd ecl:amb";"byr:2000";"eyr:2034";"cid:89 pid:934693255";"";"hcl:#b5c3db ecl:grn hgt:155cm pid:#baec97 iyr:2017";"byr:1939";"eyr:2020";"";"pid:526669252 eyr:1972";"hgt:152cm ecl:dne byr:1960 hcl:z iyr..
#+end_SRC

Different fields of a single entry are separated by either spaces, or
newlines, so we'll have to first group the entries appropriately. The
good thing is that k has some string splitting primitives built in!

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:3# i:({(`$x)!y}/ + ":"\' ,/ " "\' "\n"\)' "\n\n"\ 1:"./aoc/2020/day04.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :3# i:({(`$x)!y}/ + ":"\' ,/ " "\' "\n"\)' "\n\n"\ 1:"./aoc/2020/day04.txt"
(`hgt`iyr`hcl`ecl`byr`eyr`cid`pid!("176cm";"2013";"#fffffd";"amb";"2000";"2034";"89";"934693255")
 `hcl`ecl`hgt`pid`iyr`byr`eyr!("#b5c3db";"grn";"155cm";"#baec97";"2017";"1939";"2020")
 `pid`eyr`hgt`ecl`byr`hcl`iyr!("526669252";"1972";"152cm";"dne";"1960";,"z";"2023"))
#+end_SRC

Split by group (~\n\n~), and then for each group split by newline and
space, combine the result into a single list (via the /raze/ idiom
~,/~), and, split on a semicolon. Also, make that whole thing a
dictionary, because k natively supports that!

TODO: more

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:fst:*i
fst@`hgt / can query by key
!fst     / get all keys
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :fst:*i
!/+((`"hgt";"176cm")
    (`"iyr";"2013")
    (`"hcl";"#fffffd")
    (`"ecl";"amb")
    (`"byr";"2000")
    (`"eyr";"2034")
    (`"cid";"89")
    (`"pid";"934693255"))
 fst@`hgt / can query by key
"176cm"
 !fst     / get all keys
(`"hgt"
 `"iyr"
 `"hcl"
 `"ecl"
 `"byr"
 `"eyr"
 `"cid"
 `"pid")
#+end_SRC

The main part is finding out whether all of the required keywords are
there, and to ignore ~cid~. This just means using /without/ (~^~) and
seeing if the resulting list is of length 0.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
+/ vs:(0= #`byr`iyr`eyr`hgt`hcl`ecl`pid^ !:)'i / valid?]
#+END_SRC

#+RESULTS:
#+begin_SRC k
 +/ vs:(0= #`byr`iyr`eyr`hgt`hcl`ecl`pid^ !:)'i / valid?]
230
#+end_SRC

-----

Security is onto us! Some passports are getting through that obviously
should not, so it might be a good idea to implement some kind of
validation after all. Here are the rules:

#+begin_quote
- ~byr~ (Birth Year) - four digits; at least 1920 and at most 2002.
- ~iyr~ (Issue Year) - four digits; at least 2010 and at most 2020.
- ~eyr~ (Expiration Year) - four digits; at least 2020 and at most 2030.
- ~hgt~ (Height) - a number followed by either cm or in:
  - If cm, the number must be at least 150 and at most 193.
  - If in, the number must be at least 59 and at most 76.
- ~hcl~ (Hair Color) - a # followed by exactly six characters 0-9 or a-f.
- ~ecl~ (Eye Color) - exactly one of: amb blu brn gry grn hzl oth.
- ~pid~ (Passport ID) - a nine-digit number, including leading zeroes.
- ~cid~ (Country ID) - ignored, missing or not.
#+end_quote

#+BEGIN_SRC k
In:{((x=*|y)|x<*|y)&((x=*y)|x>*y)} / x ∈ [y₁, y₂]? k has no ≤ or ≥ by default 🙃 XXX
Ap:{(z x y)&(~&/^x y)}; Aps:{&/{Ap[x;*y;*|y]}[x]'y}
Test:{Aps[x;((`byr; {In[.x; 1920 2002]})
             (`iyr; {In[.x; 2010 2020]})
             (`eyr; {In[.x; 2020 2030]})
             (`hgt; {:["cm"~-2#x;In[.-2_x;150 193]; "in"~-2#x;In[.-2_x;59 76]; 0]})
             (`hcl; {(7=#x) & (0=#(1_x)^("a"+!6),("0"+!10)) & ("#"=*x)})
             (`ecl; (~^("amb";"blu";"brn";"gry";"grn";"hzl";"oth")?))
             (`pid; {(9=#x) & (0=#x^("0"+!10))}))]}
#+END_SRC

#+RESULTS:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
+/Test'i@&vs
#+END_SRC

#+RESULTS:
#+begin_SRC k
 +/Test'i@&vs
156
#+end_SRC

-----

Full solution:

** [[https://github.com/slotThe/advent/blob/master/aoc2020/k-solutions/day05.k][Day 5]]

Today we lost our boarding pass, and have to find our seat by process of
elimination. The input gives a binary space partitioning of the plane
for each passenger:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5# 0:"./aoc/2020/day05.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5# 0:"./aoc/2020/day05.txt"
("BFFFBBFRLR"
 "FBFFFBBLRL"
 "BFFFFFBRRR"
 "FBBBFFFLRR"
 "FFBFBFBRLL")
#+end_SRC

Our first task is to find the highest seat ID. This is described in a
wonderfully obfuscated way of translating the first seven digits into a
row ~r~, the last three digits into a column ~c~, and then doing ~c +
8*r~. Of course, what this is actually saying is that we have to
calculate the binary value of the string, with ~B~ and ~R~ being treated
as 1.

Since K does not seem to have an "element in", this is actually not as
straightforward as I would like it to be. For example, in BQN we could
just use ~∊⟜"BR"~ and be fine:

#+BEGIN_SRC bqn :results repl :exports results :wrap SRC bqn
∊⟜"BR"¨ 5↑ •FLines "./aoc/2020/day05.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC bqn
   ∊⟜"BR"¨ 5↑ •FLines "./aoc/2020/day05.txt"
⟨ ⟨ 1 0 0 0 1 1 0 1 0 1 ⟩ ⟨ 0 1 0 0 0 1 1 0 1 0 ⟩ ⟨ 1 0 0 0 0 0 1 1 1 1 ⟩ ⟨ 0 1 1 1 0 0 0 0 1 1 ⟩ ⟨ 0 0 1 0 1 0 1 1 0 0 ⟩ ⟩
#+end_SRC

The easiest way I've found to achieve this in the general case is to
just write an ~elem~ function:

#+BEGIN_SRC k
elem:{~^(y?)'x} / x elem y
#+END_SRC

#+RESULTS:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
elem[2+!10       ; 5 7 0]
elem[5 7 0       ; 2+!10]
elem["BR"        ; "BFFFBBFRLR"]
elem["BFFFBBFRLR"; "BR"]
#+END_SRC

#+RESULTS:
#+begin_SRC k
 elem[2+!10       ; 5 7 0]
0 0 0 1 0 1 0 0 0 0
 elem[5 7 0       ; 2+!10]
1 1 0
 elem["BR"        ; "BFFFBBFRLR"]
1 1
 elem["BFFFBBFRLR"; "BR"]
1 0 0 0 1 1 0 1 0 1
#+end_SRC

The fact that functions are nouns in K and thus have to be applied via
M-Expressions is, ergonomically, not super great for functions that are
meant to be read infix. As I said before, there is the option to define
the actual Unicode character ~∈~ for this, which can be used as a verb,
but I will also not make use of this feature here.

A different solution would also be to use /each left/ for checking
equality with either of the two letters, and then or the whole thing
together:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
|/ "BR"=\: 10# 0:"./aoc/2020/day05.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 |/ "BR"=\: 10# 0:"./aoc/2020/day05.txt"
(1 0 0 0 1 1 0 1 0 1
 0 1 0 0 0 1 1 0 1 0
 1 0 0 0 0 0 1 1 1 1
 0 1 1 1 0 0 0 0 1 1
 0 0 1 0 1 0 1 1 0 0
 0 1 1 0 0 1 1 0 1 1
 0 1 1 0 0 0 0 1 0 0
 1 0 0 0 1 1 0 1 0 0
 1 1 0 1 0 1 0 1 0 0
 1 0 0 0 0 0 1 1 0 0)
#+end_SRC

This at least only uses builtin verbs, but to be honest I find this
pretty difficult to read. ~elem~ it is.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:i: 2/' elem[0:"./aoc/2020/day05.txt"; "BR"]
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :i: 2/' elem[0:"./aoc/2020/day05.txt"; "BR"]
565 282 527 451 172 411 388 564 852 524 143 805 816 336 769 228 151 562 755 656 154 165 185 105 114 368 393 572 222 313 358 480 161 529 467 263 182 569 404 540 454 833 437 79 730 459 819 216 638 428 518 848 289 341 701 817 599 720 365 ..
#+end_SRC

After parsing, we can use yet another overload of the forward slash—an
(array of) integer(s) as its left argument turns it into /decode/.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
|/ i    / part one
#+END_SRC

#+RESULTS:
#+begin_SRC k
 |/ i    / part one
864
#+end_SRC

-----

For part two, we notice that the flight is completely full, with a
slight caveat. There are some additional seats in the very front and
back, which are not available in the airplane. We have to somehow find
the only seat "in the middle" of a row that's not taken yet.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:ms:(!1024)^i            / missing seats
ms[* 1_ &0= {y=x-1}':ms] / value of first middle seat
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :ms:(!1024)^i            / missing seats
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 739 865 866 867 868 ..
 ms[* 1_ &0= {y=x-1}':ms] / value of first middle seat
739
#+end_SRC

-----

Full solution:

#+BEGIN_SRC k
elem:{~^(y?)'x} / x ∈ y
i: 2/' elem[0:"./aoc/2020/day05.txt"; "BR"]
864= |/i
739= ms@*1_&0={y=x-1}':ms:(!1024)^i
#+END_SRC

#+RESULTS:

* Days 6–10

** Day 6

Today, we're helping the other passengers on the plane navigate
ridiculous customs forms. All passengers are paired into groups, and
given a list of 26 questions each. Part one asks us to identify the
questions for which anyone in the group answered "yes". The input is
grouped by group, as well as individual inside of the group (only the
"yes" answers are recorded).

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
1:"./aoc/2020/day06.txt"
,"\n\n"\ 1:"./aoc/2020/day06.txt"              / By groups
5# i: "\n"\' "\n\n"\ 1:"./aoc/2020/day06.txt" / Individual groups by line
#+END_SRC

#+RESULTS:
#+begin_SRC k
 1:"./aoc/2020/day06.txt"
1
 ,"\n\n"\ 1:"./aoc/2020/day06.txt"              / By groups
,("gsvdkufnoawjmhp\nwvhusojpnikgfadb\nvshnpfedgwajkou\naujodhskfvnpgw\nokpdnwhsfvjguqa";"juedvq\nvqeduj\nveqdju\neqduvj";"cdajbuernxm\nmnucjearxbd\naxrmdejuncb\njrebucmdxna";"kutplibdoqzfvhw\nqcewmrkdvhl\nqobdwvlkgxhpasyjn";"psbjhnatxe..
 5# i: "\n"\' "\n\n"\ 1:"./aoc/2020/day06.txt" / Individual groups by line
(("gsvdkufnoawjmhp";"wvhusojpnikgfadb";"vshnpfedgwajkou";"aujodhskfvnpgw";"okpdnwhsfvjguqa")
 ("juedvq";"vqeduj";"veqdju";"eqduvj")
 ("cdajbuernxm";"mnucjearxbd";"axrmdejuncb";"jrebucmdxna")
 ("kutplibdoqzfvhw";"qcewmrkdvhl";"qobdwvlkgxhpasyjn")
 ("psbjhnatxe";"pnaxesjhbt";"tpxhbnseaj"))
#+end_SRC

Now we can just concatenate each group, and use /distinct/, ~?X~, to get
the unique characters of the string.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
,/*i
?,/*i
#?,/*i
+/(#?,/)'i / Part one
#+END_SRC

#+RESULTS:
#+begin_SRC k
 ,/*i
"gsvdkufnoawjmhpwvhusojpnikgfadbvshnpfedgwajkouaujodhskfvnpgwokpdnwhsfvjguqa"
 ?,/*i
"gsvdkufnoawjmhpibeq"
 #?,/*i
19
 +/(#?,/)'i / Part one
6335
#+end_SRC

-----

Of course, we've actually misread the instructions! Instead of
identifying the questions to which anyone answered "yes", we need to
identify those to which /everyone/ answered "yes". This essentially
involves intersecting all of the answers for a given group, and just
counting what pops out. K does not have list intersection as a
primitive, but it does have ~\setminus~, in the form of ~X^y~.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
{x^x^y}/*i      / x^x^y is x∩y
+/(#{x^x^y}/)'i / Part two
#+END_SRC

#+RESULTS:
#+begin_SRC k
 {x^x^y}/*i      / x^x^y is x∩y
"gsvdkufnoawjhp"
 +/(#{x^x^y}/)'i / Part two
3392
#+end_SRC

-----

Full solution:

#+BEGIN_SRC k
i: "\n"\' "\n\n"\ 1:"./aoc/2020/day06.txt"
6335= +/(#?,/)'i
3392= +/(#{x^x^y}/)'i
#+END_SRC

#+RESULTS:


** Day 7

We're trying to catch our connection at a regional airport, but the
flights are delayed due to some luggage processing issues! Let's see if
we can't fix this.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5# i: " "\' 0:"./aoc/2020/day07.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5# i: " "\' 0:"./aoc/2020/day07.txt"
1
#+end_SRC

I will not write a general parser, but use lots of properties of the
input, like that bag names are always two words.

TODO: a thing about typed nulls here

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
,:f:*i                                   / first line, for testing
0N 4#f                                   / Partition
{`$,/2#*x} 0N 4#f                        / Symbols!
{(`$,/2#*x; {(.*x;`$,/2#1_x)}'1_x)} 0N 4#f / Draw the rest of the owl
#+END_SRC

#+RESULTS:
#+begin_SRC k
 ,:f:*i                                   / first line, for testing
,("plaid";"fuchsia";"bags";"contain";,"5";"light";"violet";"bags,";,"1";"light";"yellow";"bag.")
 0N 4#f                                   / Partition
(("plaid";"fuchsia";"bags";"contain")
 (,"5";"light";"violet";"bags,")
 (,"1";"light";"yellow";"bag."))
 {`$,/2#*x} 0N 4#f                        / Symbols!
`plaidfuchsia
 {(`$,/2#*x; {(.*x;`$,/2#1_x)}'1_x)} 0N 4#f / Draw the rest of the owl
(`"plaidfuchsia"
 ((5;`lightviolet);(1;`lightyellow)))
#+end_SRC

This is /almost/ correct: the only thing we still need to add are bags
that have a description like

> pale brown bags contain no other bags.

Again, having rather strong assumptions about the shape of the input helps.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
{"no"~x 4}@ " "\"pale brown bags contain no other bags."
{"no"~x 4}@ f
#+END_SRC

#+RESULTS:
#+begin_SRC k
 {"no"~x 4}@ " "\"pale brown bags contain no other bags."
1
 {"no"~x 4}@ f
0
#+end_SRC

With that, we can write our parser:

#+BEGIN_SRC k
P:{p:0N 4#x; n:`$,/2#*p
   $["no"~x 4; (n;()); {(x; {(.*x;`$,/2#1_x)}'1_y)}[n]p ]}
#+END_SRC

#+RESULTS:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
P@f
P@ " "\"pale brown bags contain no other bags."
5# i:!/ + P' " "\' 0:"./aoc/2020/day07.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 P@f
(`"plaidfuchsia"
 ((5;`lightviolet);(1;`lightyellow)))
 P@ " "\"pale brown bags contain no other bags."
(`"palebrown"
 ())
 5# i:!/ + P' " "\' 0:"./aoc/2020/day07.txt"
!/+((`"plaidfuchsia";((5;`lightviolet);(1;`lightyellow)))
    (`"stripedaqua" ;,(2;`stripedteal))
    (`"clearcoral"  ;((2;`plaidgreen);(5;`mirroredgold)))
    (`"dulltan"     ;((4;`fadedblue);(3;`fadedolive);(5;`dullsalmon)))
    (`"plaidgreen"  ;,(3;`fadedgreen)))
#+end_SRC

To find all bags that could contain ~`shinygold~, we proceed
recursively.

#+BEGIN_SRC k
/ Can bag y be contained in bag x, given the bags i?
CanCon:{bs:(i y)@'1; $[0=#bs;0; ~^bs?x;1; |/o[x;]'bs]}
#+END_SRC

#+RESULTS:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
CanCon[`dullwhite;`plaidfuchsia]
+/CanCon[`shinygold;]'!i             / Part one
#+END_SRC

#+RESULTS:
#+begin_SRC k
 CanCon[`dullwhite;`plaidfuchsia]
1
 +/CanCon[`shinygold;]'!i             / Part one
205
#+end_SRC

-----

Part two asks us how many bags are actually contained in our shiny gold
bag—the answer to which is rightfully called "topologically impractical"
:)

Implementation-wise, we again do nothing but write a simple recursive
function.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
Cnt:{bs:i x; +/$[0=#bs; 0; {x+x*Cnt[y]}/'bs]}
Cnt[`shinygold]                       / Part two
#+END_SRC

#+RESULTS:
#+begin_SRC k
 Cnt:{bs:i x; +/$[0=#bs; 0; {x+x*Cnt[y]}/'bs]}

 Cnt[`shinygold]                       / Part two
80902
#+end_SRC

I don't like that both days have this ugly base case of ~0=#bs~, but I
also don't really know how to get rid of it… Suggestions welcome!

-----

Full solution:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
P:{p:0N 4#x; n:`$,/2#*p; $["no"~x 4; (n;()); {(x; {(.*x;`$,/2#1_x)}'1_y)}[n]p ]}
i:!/+P'" "\'0:"./aoc/2020/day07.txt"
205  = +/{bs:(i y)@'1; $[0=#bs;0; ~^bs?x;1; |/o[x;]'bs]}[`shinygold;]'!i
Cnt:{bs:i x; +/$[0=#bs; 0; {x+x*Cnt[y]}/'bs]}
80902= Cnt[`shinygold]
#+END_SRC

#+RESULTS:
#+begin_SRC k
 P:{p:0N 4#x; n:`$,/2#*p; $["no"~x 4; (n;()); {(x; {(.*x;`$,/2#1_x)}'1_y)}[n]p ]}

 i:!/+P'" "\'0:"./aoc/2020/day07.txt"

 205  = +/{bs:(i y)@'1; $[0=#bs;0; ~^bs?x;1; |/o[x;]'bs]}[`shinygold;]'!i
1
 Cnt:{bs:i x; +/$[0=#bs; 0; {x+x*Cnt[y]}/'bs]}

 80902= Cnt[`shinygold]
1
#+end_SRC


** Day 8

Today we are just sitting on our flight, minding our own business, when
suddenly… the game boy of the kid next to us stops working. Obviously,
the problem is a boot loop, so we'll have to investigate further.

Our input is the boot code of the game boy, which in itself consists of
three operations, each with a mandatory argument: ~acc~, ~jmp~, and
~nop~. Before proceeding, let's quickly parse this.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:i: {(`$x 0;.(x 1)^"+")}' " "\' 0:"./aoc/2020/day08.txt"
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :i: {(`$x 0;.(x 1)^"+")}' " "\' 0:"./aoc/2020/day08.txt"
((`acc;-7)
 (`acc;2)
 (`acc;20)
 (`acc;14)
 (`jmp;191)
 (`acc;47)
 (`nop;339)
 (`acc;49)
 (`jmp;104)
 (`jmp;629)
 (`jmp;374)
 (`acc;24)
 (`jmp;220)
 (`nop;474)
 (`acc;25)
 (`jmp;340)
 (`acc;16)
 (`acc;3)
 (`acc;41)
 (`jmp;566)
 (`jmp;296)
 ..)
#+end_SRC

To execute this, we just need to get ourselves a single global value for
the ~add~ instruction, as well as a program counter for the ~jmp~. The
~nop~ instruction does nothing. Part one asks us to execute this
instruction set, and find the value of the global value before that
instruction executes.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
/ value, counter, seen, using "while" f f/
*{(v;c;s):x;^s?c}{(v;c;s):x; (a;b):i c; (v+b*`acc=a; c+(1;b)@`jmp=a; s,c)}/(0;0;,0N)
#+END_SRC

#+RESULTS:
#+begin_SRC k
 / value, counter, seen, using "while" f f/

 ,*{(v;c;s):x;^s?c}{(v;c;s):x; (a;b):i c; (v+b*`acc=a; c+(1;b)@`jmp=a; s,c)}/(0;0;,0N)
1594
#+end_SRC

Notation is a bit awkward, since K (well, at least ~ngn/k~) does not
support pattern matching in function headers, and I haven't found a good
way around this yet. Oh well.

-----

Against all odds, the noop is actually a noop! However, we get the
prescient feeling that exactly one ~jmp~ instruction should be a ~nop~,
or the other way around, so that the program can exit cleanly. We just
have to find out which instruction to flip.

Let's see how many different paths we'd have to check.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
#&|/`jmp`nop=\:*'i / How many jumps or noops?
#+END_SRC

#+RESULTS:
#+begin_SRC k
 #&|/`jmp`nop=\:*'i / How many jumps or noops?
291
#+end_SRC

This code uses the ~|/X=\:~ idiom which I skipped for readability reasons on
day 5—funny how these things work. Anyways, with just ~300 simulations,
this part seems destined to be brute-forced.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
is:@[i;;{(*`jmp`nop^x 0;x 1)}]'&|/`jmp`nop=\:*'i; / instructions
mx:-1+#i                                          / max instruction count
While:{(v;c;s;j):x;(^s?c)&(c<mx)}                 / loop while this is true
Do:{(v;c;s;j):x; (a;b):j c; (v+b*`acc=a; c+(1;b)@`jmp=a; s,c; j)}
**{mx=x@'1}# {While Do/(0;0;,0N;x)}'is            / filter for successful exit
#+END_SRC

#+RESULTS:
#+begin_SRC k
 is:@[i;;{(*`jmp`nop^x 0;x 1)}]'&|/`jmp`nop=\:*'i; / instructions

 mx:-1+#i                                          / max instruction count

 While:{(v;c;s;j):x;(^s?c)&(c<mx)}                 / loop while this is true

 Do:{(v;c;s;j):x; (a;b):j c; (v+b*`acc=a; c+(1;b)@`jmp=a; s,c; j)}

 ,**{mx=x@'1}# {While Do/(0;0;,0N;x)}'is            / filter for successful exit
758
#+end_SRC

-----

Full solution:

#+BEGIN_SRC k
i:{(`$x 0;.(x 1)^"+")}' " "\' 0:"./aoc/2020/day08.txt";  mx:-1+#i
While:{(v;c;s;j):x; (^s?c)&(c<mx)}
Do:{(v;c;s;j):x; (a;b):j c; (v+b*`acc=a; c+(1;b)@`jmp=a; s,c; j)}
Sol:{While Do/(0;0;,0N;x)}
1594= *           Sol i
758 = **{mx=x@'1}#Sol'@[i;;{(*`jmp`nop^x 0;x 1)}]'&|/`jmp`nop=\:*'i
#+END_SRC

#+RESULTS:

** Day 9

After using several paperclips to connect our computer to our in-flight
screen, we're trying to break the encryption of its open data port.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:i:.'0:"./aoc/2020/day09.txt" / .C is eval
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :i:.'0:"./aoc/2020/day09.txt" / .C is eval
1
#+end_SRC

The data is encrypted with the whimsically named "eXchange-Masking
Addition System"; it starts off by transmitting 25 numbers, and after
that every number that follows is a sum of two of the previous 25
numbers.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
#i
#+END_SRC

#+RESULTS:
#+begin_SRC k
 #i
1000
#+end_SRC

Only 1000 numbers means we're probably able to just brute-force this,
in a similar way to what we did for day 1.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:p1: i@ 25+ *& {~|//(*|x)=as+/:as:-1_x}' 26':i / Part one
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :p1: i@ 25+ *& {~|//(*|x)=as+/:as:-1_x}' 26':i / Part one
1930745883
#+end_SRC

#+RESULTS:
: 1930745883

Here, I used /windows/ (~i':~) and /converge/ (~f/~), which I think are
pretty self-explanatory. Indeed, using converge with a fold as a
function is relatively common for doing things like flattening arrays:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
5 5#!25    / Array
+/5 5#!25  / Column rums
+//5 5#!25 / Array sum
#+END_SRC

#+RESULTS:
#+begin_SRC k
 5 5#!25    / Array
(0 1 2 3 4
 5 6 7 8 9
 10 11 12 13 14
 15 16 17 18 19
 20 21 22 23 24)
 +/5 5#!25  / Column rums
50 55 60 65 70
 +//5 5#!25 / Array sum
300
#+end_SRC

-----

Having found ~p1~, we are now tasked to find a /contiguous/ set of two
numbers that sum up to it. Problems like this can usually quite neatly
be solved using a simple sliding window approach: start with a window
size at the start of the array, grow the window as long as the sum is
smaller or equal to the target, and shrink the window (from the back)
when it's bigger.

This additional complexity is not actually needed here, and I'm just
going to brute-force this: calculate the full sum scan of ~i~, ~1_i~,
and so on and find the correct offset based on that. That's only, like,
10000 numbers to check, which sounds fast enough to do that instead.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
{+\x_t}'!#t:35 20 15 25 47 40 62 / Test input
+&{127=+\x_t}'!#t                / Gets the row and offset
#+END_SRC

#+RESULTS:
#+begin_SRC k
 {+\x_t}'!#t:35 20 15 25 47 40 62 / Test input
(35 55 70 95 142 182 244
 20 35 60 107 147 209
 15 40 87 127 189
 25 72 112 174
 47 87 149
 40 102
 ,62)
 +&{127=+\x_t}'!#t                / Gets the row and offset
,2 3
#+end_SRC

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:(r;of): *+&{p1=+\x_i}'!#i / Now for the actual input
{(&/x)+|/x}(of+1)#r_i      / Part two
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :(r;of): *+&{p1=+\x_i}'!#i / Now for the actual input
553 16
 {(&/x)+|/x}(of+1)#r_i      / Part two
268878261
#+end_SRC

-----

Full solution:

#+BEGIN_SRC k
i:.'0:"./aoc/2020/day09.txt"
1930745883= p1: i@ 25+ *&{~|//(*|x)=as+/:as:-1_x}' 26':i
(r;of): *+&{p1=+\x_i}'!#i
268878261 = {(&/x)+|/x}(of+1)#r_i
#+END_SRC

#+RESULTS:

** Day 10

Just as we discover the weather forecasts of a massive tropical storm,
our battery dies! We'll have to charge it using the weird charging
outlets on the plane. We'll use a number of adapters that we have with
us to transform the joltage levels to something our computer can work
with. Our puzzle input consists of the output joltage each adapter can
handle.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:i:i@<i:.'0:"./aoc/2020/day10.txt"
#i
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :i:i@<i:.'0:"./aoc/2020/day10.txt"
1
 #i
101
#+end_SRC

Additionally, our device has a built-in adapter three jolts higher than
the highest one in the input. The outlet has joltage level 0. Every
adapter can only be connected to a source 1-3 jolts lower than its
rating. Part one asks us to use every adapter in the bag (plus the one
we have), count the number of 1-jolt and 3-jolt differences, and add
them up.

Since we have to use every adapter once, there's not actually much to do
here. We just have to compute how far each element is away from its
predecessor, which is conveniently done with /eachprior/ ~F':~:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
:d:3+|/i
-':i,d         / Differences, initial 0 is implicit
=-':i,d        / Group =X
,*/ #' =-':i,d / Part one
#+END_SRC

#+RESULTS:
#+begin_SRC k
 :d:3+|/i
164
 -':i,d         / Differences, initial 0 is implicit
1 1 1 1 3 3 1 1 1 1 3 1 1 1 1 3 1 1 1 1 3 1 1 1 1 3 1 1 3 3 1 1 1 3 1 1 1 1 3 3 1 1 1 1 3 3 1 3 1 1 3 1 1 1 3 1 1 1 3 1 1 1 3 3 1 1 1 3 1 1 1 3 3 3 1 1 1 3 1 1 1 3 3 3 1 1 1 1 3 1 1 1 3 1 1 1 1 3 1 1 1 3
 =-':i,d        / Group =X
!/+((1;0 1 2 3 6 7 8 9 11 12 13 14 16 17 18 19 21 22 23 24 26 27 30 31 32 34 35 36 37 40 41 42 43 46 48 49 51 52 53 55 56 57 59 60 61 64 65 66 68 69 70 74 75 76 78 79 80 84 85 86 87 89 90 91 93 94 95 96 98 99 100)
    (3;4 5 10 15 20 25 28 29 33 38 39 44 45 47 50 54 58 62 63 67 71 72 73 77 81 82 83 88 92 97 101))
 ,*/ #' =-':i,d / Part one
2201
#+end_SRC

-----

Instead of some terrible optimisation problem, part two involves
counting the number of ways that we can connect the outlet ~0~ to our
device ~d~, now not necessarily using every adapter. Essentially, every
time there is a ~1~ instead of a ~3~ in the differences above, we have
the opportunity to leave out that specific adapter. Obviously—and in
fact, we're even told that our solution will be more than a
trillion—this results in a bit of a combinatorial explosion; we'll have
to come up with a smart plan instead.

Looking at the differences again, we see a curious pattern:

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
-':i,d
#+END_SRC

#+RESULTS:
#+begin_SRC k
 -':i,d
1 1 1 1 3 3 1 1 1 1 3 1 1 1 1 3 1 1 1 1 3 1 1 1 1 3 1 1 3 3 1 1 1 3 1 1 1 1 3 3 1 1 1 1 3 3 1 3 1 1 3 1 1 1 3 1 1 1 3 1 1 1 3 3 1 1 1 3 1 1 1 3 3 3 1 1 1 3 1 1 1 3 3 3 1 1 1 1 3 1 1 1 3 1 1 1 1 3 1 1 1 3
#+end_SRC

All adapters have distance one or three, no twos in sight. The threes
thus function as a sort of "reset point": they can't themselves be
touched by the surrounding adapters, so we can treat each group of ones
as its own little island. The rules for each island are simple: we can't
remove anything from the front or back, and in the middle we can remove
at most two numbers. For example:

#+BEGIN_SRC
  3 1 1 1 3     # This is a possible "island" of offsets
-3 0 1 2 3 6    # All of these would be valid
-3 0 1   3 6
-3 0   2 3 6
-3 0     3 6
#+END_SRC

This is the number of binary sequences with at most two ones, which can
for example be calculated using \(\sum_{i=0}^2 {n \choose i}\), where \(n\) is the length of the sequence. Since our sequences are only
of length one, two, three, or four, I'll just hard-code the only two
numbers we need to care about here: ~7=1+3+3~ for ~3 1 1 1 1 3~ and
~4=1+2+1~ for ~3 1 1 1 3~.

#+BEGIN_SRC k :results repl :exports results :wrap SRC k
,"3"\,/$-':i,d                             / Better solutions welcome!
,*/ {$[x=4;7;x=3;4;1|x]}' #' "3"\,/$-':i,d / Part two
#+END_SRC

#+RESULTS:
#+begin_SRC k
 ,"3"\,/$-':i,d                             / Better solutions welcome!
,("1111";"";"1111";"1111";"1111";"1111";"11";"";"111";"1111";"";"1111";"";,"1";"11";"111";"111";"111";"";"111";"111";"";"";"111";"111";"";"";"1111";"111";"1111";"111";"")
 ,*/ {$[x=4;7;x=3;4;1|x]}' #' "3"\,/$-':i,d / Part two
169255295254528
#+end_SRC

-----

Full solution:

#+BEGIN_SRC k
i:i@<i:.'0:"./aoc/2020/day10.txt"
2201= */#'=d:-':i,3+|/i
169255295254528= */{$[x=4;7;x=3;4;1|x]}'#'"3"\,/$d
#+END_SRC

#+RESULTS:

* Days 11–15

** Day 11

** Day 12

#+begin_SRC k :results repl :exports results :wrap SRC k
:i:{(`$*x;.1_x)}'0:"./aoc/2020/day12.txt"
#+end_SRC

#+RESULTS:
#+begin_SRC k
 :i:{(`$*x;.1_x)}'0:"./aoc/2020/day12.txt"
((`W;1)
 (`F;91)
 (`W;3)
 (`F;82)
 (`N;1)
 (`E;2)
 (`N;4)
 (`R;90)
 (`F;25)
 (`N;2)
 (`F;75)
 (`E;4)
 (`R;90)
 (`F;91)
 (`R;90)
 (`F;64)
 (`L;90)
 (`E;1)
 (`L;90)
 (`S;2)
 (`L;180)
 ..)
#+end_SRC

#+begin_SRC k :results repl :exports results :wrap SRC k
p::0 0; d::0 1; rot:{((-y;x);(-x;-y);(y;-x))}; T:{(rot/d)@90 180 270?x};
{$[`N=x;p+:y*-1 0; `S=x;p+:y*1 0; `W=x;p+:y*0 -1; `E=x;p+:y*0 1; `F=x;p+:y*d; `L=x;d::T[y]; `R=x;d::T[360-y]]}/'i;
+/p|-p
#+end_SRC

#+RESULTS:
#+begin_SRC k
 p::0 0; d::0 1; rot:{((-y;x);(-x;-y);(y;-x))}; T:{(rot/d)@90 180 270?x};

 {$[`N=x;p+:y*-1 0; `S=x;p+:y*1 0; `W=x;p+:y*0 -1; `E=x;p+:y*0 1; `F=x;p+:y*d; `L=x;d::T[y]; `R=x;d::T[360-y]]}/'i;

 +/p|-p
1294
#+end_SRC

#+begin_SRC k :results repl :exports results :wrap SRC k
wp::-1 10; p::0 0; d::0 1; rot:{((-y;x);(-x;-y);(y;-x))}; T:{(rot/wp)@90 180 270?x};
{$[`N=x;wp+:y*-1 0; `S=x;wp+:y*1 0; `W=x;wp+:y*0 -1; `E=x;wp+:y*0 1; `F=x;p+:y*wp; `L=x;wp::T[y]; `R=x;wp::T[360-y]]}/'i;
(wp;p;d)
+/p|-p
#+end_SRC

#+RESULTS:
#+begin_SRC k
 wp::-1 10; p::0 0; d::0 1; rot:{((-y;x);(-x;-y);(y;-x))}; T:{(rot/wp)@90 180 270?x};

 {$[`N=x;wp+:y*-1 0; `S=x;wp+:y*1 0; `W=x;wp+:y*0 -1; `E=x;wp+:y*0 1; `F=x;p+:y*wp; `L=x;wp::T[y]; `R=x;wp::T[360-y]]}/'i;

 (wp;p;d)
(10 -6
 2726 -17866
 0 1)
 +/p|-p
20592
#+end_SRC

** Day 13

We are about to reach a nearby port, only to discover that no ships
actually go to our vacation island. Time for another plane.[fn:13]
Thankfully, there is a whole array of buses that go to and from the
airport—each bus ID indicates the intervals at which it leaves, starting
from a fixed timestamp ~0~ at which every bus leaves (must've been quite
the spectacle!).

#+begin_SRC k :results repl :exports results :wrap SRC k
:(t;bf):{`I$'(x 0;","\x 1)}@0:"./aoc/2020/day13.txt" /timestamp and busses filled
:ib:&~^bf                                            /indices of busses
:bs:bf^0N                                            /busses
#+end_SRC

#+RESULTS:
#+begin_SRC k
 :(t;bf):{`I$'(x 0;","\x 1)}@0:"./aoc/2020/day13.txt" /timestamp and busses filled
(1008832
 23 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 41 0N 0N 0N 0N 0N 0N 0N 0N 0N 449 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 13 19 0N 0N 0N 0N 0N 0N 0N 0N 0N 29 0N 991 0N 0N 0N 0N 0N 37 0N 0N 0N 0N 0N 0N 0N 0N 0N 0N 17)
 :ib:&~^bf                                            /indices of busses
0 13 23 41 42 52 54 60 71
 :bs:bf^0N                                            /busses
23 41 449 13 19 29 991 37 17
#+end_SRC

The first number is the earliest timestamp at which we would be able to
leave. The first part of the question asks us to find the unique
earliest bus that would take us to the airport, and multiply that by
how many minutes after the given timestamp that bus leaves. This isn't so
bad: starting from timestamp \(t\), we're looking for that bus \(b\) for
which \(t-b \mod b\) is minimal.

#+begin_SRC k :results repl :exports results :wrap SRC k
{x!x-t}'bs                 /all offsets
&/{x!x-t}'bs               /minimum
is?&/is:{x!x-t}'bs         /index of minimum
{x*bs@x}is?&/is:{x!x-t}'bs /part one
#+end_SRC

#+RESULTS:
#+begin_SRC k
 {x!x-t}'bs                 /all offsets
17 14 71 7 11 20 6 10 16
 &/{x!x-t}'bs               /minimum
6
 is?&/is:{x!x-t}'bs         /index of minimum
6
 {x*bs@x}is?&/is:{x!x-t}'bs /part one
5946
#+end_SRC

I believe I've never used /find/, ~X?y~, before this point, but it very
much does what it says on the tin: it looks through the array to find
the first occurrence of the given element, and either returns the index,
or NULL if the element is not in the array.

#+begin_SRC k :results repl :exports results :wrap SRC k
1 2 3 4 ? 4 1 0 6 7
"abc"?"ad"
#+end_SRC

#+RESULTS:
#+begin_SRC k
 1 2 3 4 ? 4 1 0 6 7
3 0 0N 0N 0N
 "abc"?"ad"
0 0N
#+end_SRC

-----

It's a maths day—rejoice!

Having found our bus, we're taking part in the shuttle companies' contest:

#+begin_quote
one gold coin for anyone that can find the earliest timestamp such that
the first bus ID departs at that time and each subsequent listed bus ID
departs at that subsequent minute.
[…]
An ~x~ in the schedule means there are no constraints on what bus IDs must
depart at that time.
#+end_quote

So given something like ~7,13,x,x,59,x,31,19~ we must have that ID ~7~
departs at timestamp ~t~, ~13~ departs at ~t+1~, ~59~ departs at ~t+4~,
and so on.

If you stare at this enough, you conveniently realise that the numbers
above are all prime. In particular, we are looking for a number \(t\),
such that

\[\begin{aligned}
    t &\equiv 0 \mod 7 \\
    t &\equiv 1 \mod 13\\
    t &\equiv 4 \mod 59\\
    t &\equiv 6 \mod 31\\
    t &\equiv 7 \mod 19
  \end{aligned} \]

If you're thinking of the [[https://en.wikipedia.org/wiki/Chinese_remainder_theorem][Chinese remainder theorem]] at this point, you'd
be exactly right! If a single line is \(t \equiv a_i \mod n_i\), then the
usual algorithm to find a solution goes like this:

1. Define \(N = \mathrm{lcm}\,{\{n_i\}}_i\); if all \(n_i\) are prime (which is the case here), this is just their product.
2. Compute \(m_i = a_i / N\) for all \(i\).
3. Compute the inverse \(x_i\) of \(m_i\) mod \(n_i\) for all \(i\).
4. The solution is any \(t \equiv \sum_i a_i \cdot m_i \cdot x_i \mod N\).

Our K solution will follow this algorithm; the \(a_i\) are just the bus IDs
minus their indexes, and the rest translates essentially verbatim.

#+begin_SRC k :results repl :exports results :wrap SRC k
ai:bs-ib
mi:(-bs)!'N:*/bs            /Defining N here
xi:*'&'1=bs!'(!'bs)*bs!'mi
N!+/ai*mi*xi /part two
#+end_SRC

#+RESULTS:
#+begin_SRC k
 ai:bs-ib

 mi:(-bs)!'N:*/bs            /Defining N here

 xi:*'&'1=bs!'(!'bs)*bs!'mi

 N!+/ai*mi*xi /part two
645338524823718
#+end_SRC

-----

Full solution:

#+begin_SRC k
(t;bf):{`I$'(x 0;","\x 1)}@0:"./aoc/2020/day13.txt"; ib:&~^bf; bs:bf^0N
5946= {x*bs@x}is?&/is:{x-x!t}'bs
ai:bs-ib; mi:(-bs)!'N:*/bs; xi:*'&'1=bs!'(!'bs)*bs!'mi
645338524823718= N!+/ai*mi*xi
#+end_SRC

#+RESULTS:

** Day 14

We're now really, really, about to reach the sea port. However, the
captain needs our help to fix the docking program on the ferry, so that
it works with the port's computer system. The system initialises some
memory using a custom bitmask system, which we'll need to emulate in
software.

The input looks like this:

#+begin_src
mask = 000000000000000000000000000000X1001X
mem[42] = 100
mask = 00000000000000000000000000000000X0XX
mem[26] = 1
#+end_src

A line defining the current mask, followed by one or more lines of
memory assignments. The mask is given in big endian order, and acts upon
the values of the memsets, which we'll have to transform to binary
before modifying them. A ~0~ or a ~1~ in the mask means to override the
bit of the value in the respective position, while an ~X~ indicates no
change.

I think this is most elegantly done with two masks: one for all of the
zeros, and one for all of the ones. Let's write a parsing function
that sets two global variables, ~gz~ and ~go~:

#+begin_SRC k :results repl :exports results :wrap SRC k
"01"=\:"XXX000111X"
Msk:{(gz;go)::"01"=\:7_x} /drop "mask = " prefix
Msk "mask = 000000000000000000000000000000X1001X"; (gz;go)
#+end_SRC
#+RESULTS:
#+begin_SRC k
 "01"=\:"XXX000111X"
1
 Msk:{(gz;go)::"01"=\:7_x} /drop "mask = " prefix

 Msk "mask = 000000000000000000000000000000X1001X"; (gz;go)
(1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0)
#+end_SRC

Hackily parsing a memset line is relatively straightforward:

#+begin_SRC k :results repl :exports results :wrap SRC k
en:`I$ 4 3_' "]"\ "mem[42] = 100" /extract numbers
{((36-#a)#0),a:2\y}/en           /pad 2nd number to 36 bits
#+end_SRC

#+RESULTS:
#+begin_SRC k
 en:`I$ 4 3_' "]"\ "mem[42] = 100" /extract numbers

 {((36-#a)#0),a:2\y}/en           /pad 2nd number to 36 bits
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0
#+end_SRC

Setting the memory works with another global variable; a dict that holds
associations of a memory address with its value.

#+begin_SRC k :results repl :exports results :wrap SRC k
mem::(!0)!!0
Mem:{mem[x]:2/(~gz)&go|((36-#a)#0),a:2\y}/`I$4 3_'"]"\
Msk "mask = 000000000000000000000000000000X1001X";
Mem "mem[42] = 100"
mem
#+end_SRC

#+RESULTS:
#+begin_SRC k
 mem::(!0)!!0

 Mem:{mem[x]:2/(~gz)&go|((36-#a)#0),a:2\y}/`I$4 3_'"]"\

 Msk "mask = 000000000000000000000000000000X1001X";

 Mem "mem[42] = 100"

 mem
(,42)!,50
#+end_SRC

The maths seems to check out, at least:

#+begin_src
value:  000000000000000000000000000001100100  (dec 100)
mask:   000000000000000000000000000000X1001X
result: 000000000000000000000000000000110010  (dec 50)
#+end_src

Now that we have the two functions, we just need to evaluate the input
line by line, and sum up all memory values at the end:

#+begin_SRC k :results repl :exports results :wrap SRC k
mem::(!0)!!0
{$["mask"~4#x;Msk x;Mem x]}'0:"./aoc/2020/day14.txt";
+/mem
#+end_SRC

#+RESULTS:
#+begin_SRC k
 mem::(!0)!!0

 {$["mask"~4#x;Msk x;Mem x]}'0:"./aoc/2020/day14.txt";

 +/mem
10452688630537
#+end_SRC

-----

We simulated the wrong decoder chip, of course, and instead need to
program version two! Instead of the memory address, the mask now works
on the value of the memset. Also, the rules are slightly different: now,
we have to change the memory address, and ~0~ leaves the bit unchanged,
~1~ overwrites it with ~1~, and an ~X~ creates two separate memory
writes: one for the string with ~X~ replaced by ~0~, and one for
~1~.[fn:14] In particular, the mask is first applied to the value before we
can begin "processing" all of the alternatives.

When parsing this, we can make use of the fact that, as opposed to
something like BQN's ~•BQN~, K's evaluation via ~.C~ works inside the
current scope. In particular, we can try to define ~X~ to be any value
we want, and evaluate the string character-by-character to immediately
turn it into an integer array! Hacky, certainly, but the fun kind of
hacky!

#+begin_SRC k :results repl :exports results :wrap SRC k
X:2
.'"XXX000111X" /eval each
#+end_SRC

#+RESULTS:
#+begin_SRC k
 X:2

 .'"XXX000111X" /eval each
2 2 2 0 0 0 1 1 1 2
#+end_SRC

Assuming we have a string like ~2220001112~, the strategy that I went
with is to just split at every ~2~ and create two new strings, one for
each possible outcome.

#+begin_SRC k :results repl :exports results :wrap SRC k
s:1 0 2 2 0 0 0 1 1 1 2
&X=s                               /indices of 2's
1_'(b:&X=s)_s                      /cut at indices and drop 2's
(0 1,\:1_)'(b:&X=s)_s              /two possible worlds
{,/(x,\:)'y}/(0 1,\:1_)'(b:&X=s)_s /combine to all possible combs
(s[!*b],)'{,/(x,\:)'y}/(0 1,\:1_)'(b:&X=s)_s /add back first part
#+end_SRC

#+RESULTS:
#+begin_SRC k
 s:1 0 2 2 0 0 0 1 1 1 2

 &X=s                               /indices of 2's
2 3 10
 1_'(b:&X=s)_s                      /cut at indices and drop 2's
(!0
 0 0 0 1 1 1
 !0)
 (0 1,\:1_)'(b:&X=s)_s              /two possible worlds
((,0;,1)
 (0 0 0 0 1 1 1;1 0 0 0 1 1 1)
 (,0;,1))
 {,/(x,\:)'y}/(0 1,\:1_)'(b:&X=s)_s /combine to all possible combs
(0 0 0 0 0 1 1 1 0
 1 0 0 0 0 1 1 1 0
 0 1 0 0 0 1 1 1 0
 1 1 0 0 0 1 1 1 0
 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 1 1
 0 1 0 0 0 1 1 1 1
 1 1 0 0 0 1 1 1 1)
 (s[!*b],)'{,/(x,\:)'y}/(0 1,\:1_)'(b:&X=s)_s /add back first part
(1 0 0 0 0 0 0 1 1 1 0
 1 0 1 0 0 0 0 1 1 1 0
 1 0 0 1 0 0 0 1 1 1 0
 1 0 1 1 0 0 0 1 1 1 0
 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 1 1 1 1
 1 0 0 1 0 0 0 1 1 1 1
 1 0 1 1 0 0 0 1 1 1 1)
#+end_SRC

So, all in all we have:

#+begin_SRC k
Cs:{(2/x[!*a],)'{,/(x,\:)'y}/(0 1,\:1_)'(a:&X=x)_x} /combinations
#+end_SRC

#+RESULTS:

I also added in a ~2/~ at the very end, so that we get decimal numbers
out of ~Cs~, instead of binary strings.

The ~Mem~ function for part two looks essentially like the first one,
only we do the bitstring processing on the address part, instead of the
value one.

#+begin_SRC k :results repl :exports results :wrap SRC k
X:2; Msk:{msk::.'7_x}
mem::(!0)!!0
Mem:{mem,: ![;y] Cs msk|((36-#a)#0),a:2\x}/`I$4 3_'"]"\
Msk "mask = 000000000000000000000000000000X1001X"
Mem "mem[10] = 94"
mem
#+end_SRC

#+RESULTS:
#+begin_SRC k
 X:2; Msk:{msk::.'7_x}

 mem::(!0)!!0

 Mem:{mem,: ![;y] Cs msk|((36-#a)#0),a:2\x}/`I$4 3_'"]"\

 Msk "mask = 000000000000000000000000000000X1001X"

 Mem "mem[10] = 94"

 mem
!/+((26;94)
    (58;94)
    (27;94)
    (59;94))
#+end_SRC

Execution works exactly as before.

#+begin_SRC k :results repl :exports results :wrap SRC k
mem::(!0)!!0
{$["mask"~4#x;Msk x;Mem x]}'0:"./aoc/2020/day14.txt";
+/mem /part two
#+end_SRC

#+RESULTS:
#+begin_SRC k
 mem::(!0)!!0

 {$["mask"~4#x;Msk x;Mem x]}'0:"./aoc/2020/day14.txt";

 +/mem /part two
2881082759597
#+end_SRC

#+RESULTS:

-----

Full solution:

#+begin_SRC k :results repl :exports results :wrap SRC k
mem:(!0)!!0; X:2; mem2:(!0)!!0
Cs:{(2/x[!*a],)'{,/(x,\:)'y}/(0 1,\:1_)'(a:&X=x)_x} /combinations
Msk:{(gz;go)::"01"=\:7_x}; Msk2:{msk::.'7_x}
Mem:{mem[x]: 2/(~gz)&go|((36-#a)#0),a:2\y}/`I$4 3_'"]"\
Mem2:{mem2,:![;y]Cs msk|((36-#a)#0),a:2\x}/`I$4 3_'"]"\
{$["mask"~4#x;[Msk x;Msk2 x];[Mem x;Mem2 x]]}'0:"./aoc/2020/day14.txt";
10452688630537 2881082759597~ +/'(mem;mem2)
#+end_SRC

#+RESULTS:
#+begin_SRC k
 mem:(!0)!!0; X:2; mem2:(!0)!!0

 Cs:{(2/x[!*a],)'{,/(x,\:)'y}/(0 1,\:1_)'(a:&X=x)_x} /combinations

 Msk:{(gz;go)::"01"=\:7_x}; Msk2:{msk::.'7_x}

 Mem:{mem[x]: 2/(~gz)&go|((36-#a)#0),a:2\y}/`I$4 3_'"]"\

 Mem2:{mem2,:![;y]Cs msk|((36-#a)#0),a:2\x}/`I$4 3_'"]"\

 {$["mask"~4#x;[Msk x;Msk2 x];[Mem x;Mem2 x]]}'0:"./aoc/2020/day14.txt";

 10452688630537 2881082759597~ +/'(mem;mem2)
1
#+end_SRC

* Footnotes

[fn:14] I'm surprised that there's no joke about multiple realities at this point.

[fn:13] I wonder what the carbon footprint is for this journey.

[fn:12] Several more mainstream languages that are inspired by array languages, like numpy, julia, or R, call this "broadcasting".

[fn:10] One could technically also just define them—at least ~ngn/k~ allows
    one to define new verbs as Unicode symbols, but I feel like this
    sort of goes against the spirit of the language, so I won't make
    much use of this functionality, if only so I don't immediately turn this
    language into a weird version of BQN.

    #+BEGIN_SRC k :results repl :exports results :wrap SRC k
    (≤):{(x=y)|x<y}      / or x<y+1
    (!9) ≤ 1,(!4),5,6+!3
    #+END_SRC

    #+RESULTS:
    #+begin_SRC k
     (≤):{(x=y)|x<y}      / or x<y+1

     (!9) ≤ 1,(!4),5,6+!3
    1 0 0 0 0 1 1 1 1
    #+end_SRC

#+RESULTS:


[fn:1] These are the first few words I write, and I'm deliberately not editing them later. This means you are now able to judge how I did.

[fn:2] Which I'm always glad to hear about!

[fn:3] Yes, that is a forward slash /followed by a space/. More on this insanity later.

[fn:4] Another use for ~:~ is TODO

[fn:5] Did I mention just how /insane/ this language is? Maybe that's why it's so fun :)

[fn:6] It's times like these that I'm so glad that BQN has this weird case-based syntax for syntactic classes. Makes things much clearer after the initial acclimation phase.

[fn:7] Note that K does not go so hard in the direction of combinators, as BQN or APL might. You won't find 3-trains like ~w(FGH)x ≡ (wFx)G(wHx)~ here.

[fn:8] Notice in particular that the colon on the very right is /not/ indicating a monadic use, but is instead part of /each left/.

[fn:9] This is the array language equivalent of composing reflections to get rotations—a fact that every algebra student has seen at some point, though possibly not in this guise.
